-- AlterTable
ALTER TABLE `TaskAssignee` ADD COLUMN `completedAt` DATETIME(3) NULL,
    ADD COLUMN `progress` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `startedAt` DATETIME(3) NULL,
    ADD COLUMN `status` ENUM('TODO', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED') NOT NULL DEFAULT 'TODO';
